pipeline {
    agent none // 각 스테이지에서 동적으로 에이전트를 선택할 수 있도록 전역 에이전트 비활성화

    stages {
        stage('Deploy dev server') {
            when {
                branch 'develop' // develop 브랜치에서 변경 사항이 발생한 경우
            }
            agent { label 'dev' } // dev 라벨이 할당된 에이전트 (mimo-dev 노드)
            steps {
                echo 'Deploying to Development Environment'
            }
        }
        stage('Deploy ops server') {
            when {
                branch 'master' // master 브랜치에서 변경 사항이 발생한 경우
            }
            agent { label 'ops' } // ops 라벨이 할당된 에이전트 (mimo-ops 노드)
            steps {
                echo 'Deploying to Production Environment'
            }
        }
    }
    post {
        always {
            echo 'Build completed'
        }
    }
}

